
<Output>           
CFL                 0.9
limit_time          0.3
limit_dt            2

<Mesh>             
x1_beg              0.0
x1_end              1.0
nx1                 32
nghost              2
x1_inner_bc         outflow
x1_outer_bc         outflow

<Problem>          
problem             sin_wave
reconstruction      2
slope_type          mc_limiter
method              TVD
left_speed          2
right_speed         -1
